"""
CHASSIS Game — Real-World Parts Database
All parts use real-world specifications where available.
"""

from models import (
    Engine, Chassis, Turbo, Transmission, SuspensionKit,
    Wheel, Tire, ECU, Part,
    Dimensions, EngineBay,
    PartCategory, DrivetrainType, AspirationMode, CylinderConfig,
)

# ═══════════════════════════════════════════════════════════════
#  ENGINES  (25 real powerplants)
# ═══════════════════════════════════════════════════════════════

ENGINES: list[Engine] = [

    Engine(
        id="bmw_s58",
        name="BMW S58 B30T0",
        brand="BMW M",
        category=PartCategory.ENGINE,
        description="The fire-breathing heart of the BMW M3/M4 Competition. Twin-turbo inline-six with S1000RR-derived head tech. Close to 500 hp stock, enormous headroom.",
        dimensions=Dimensions(length_mm=660, width_mm=595, height_mm=630),
        weight_kg=193,
        price_usd=28000,
        displacement_cc=2993,
        cylinder_count=6,
        cylinder_config=CylinderConfig.I6,
        aspiration=AspirationMode.TWIN_TURBO,
        fuel_type="Gasoline / E50",
        horsepower_stock=503,
        torque_nm_stock=650,
        redline_rpm=7200,
        idle_rpm=700,
        boost_psi_stock=22.0,
        compression_ratio=9.3,
        firing_order="1-5-3-6-2-4",
        horsepower_potential=900,
        torque_potential_nm=1100,
        cooling_requirement_kw=45,
        oil_capacity_liters=6.5,
        notes="Requires BMW S58-spec engine mounts. High electrical demand (48V mild hybrid in OEM form).",
    ),

    Engine(
        id="toyota_2jz_gte",
        name="Toyota 2JZ-GTE",
        brand="Toyota",
        category=PartCategory.ENGINE,
        description="Legendary 3.0L iron-block twin-turbo inline-six from the A80 Supra. The gold standard of engine swaps. Near-stock blocks have held 1000 hp on stock internals.",
        dimensions=Dimensions(length_mm=630, width_mm=560, height_mm=700),
        weight_kg=245,
        price_usd=12000,
        displacement_cc=2997,
        cylinder_count=6,
        cylinder_config=CylinderConfig.I6,
        aspiration=AspirationMode.TWIN_TURBO,
        fuel_type="Gasoline / E85",
        horsepower_stock=320,
        torque_nm_stock=431,
        redline_rpm=6800,
        idle_rpm=800,
        boost_psi_stock=10.0,
        compression_ratio=8.5,
        firing_order="1-5-3-6-2-4",
        horsepower_potential=1200,
        torque_potential_nm=1400,
        cooling_requirement_kw=38,
        oil_capacity_liters=5.5,
        notes="Extremely popular swap engine. Aftermarket support is massive. Stock bottom end handles 700 hp reliably.",
    ),

    Engine(
        id="nissan_rb26dett",
        name="Nissan RB26DETT",
        brand="Nissan",
        category=PartCategory.ENGINE,
        description="2.6L DOHC twin-turbo inline-six from the Skyline GT-R. Factory limited to 276 hp (gentleman's agreement) but makes 320+ stock. Iconic sound.",
        dimensions=Dimensions(length_mm=650, width_mm=530, height_mm=720),
        weight_kg=258,
        price_usd=14000,
        displacement_cc=2568,
        cylinder_count=6,
        cylinder_config=CylinderConfig.I6,
        aspiration=AspirationMode.TWIN_TURBO,
        fuel_type="Gasoline / E85",
        horsepower_stock=330,
        torque_nm_stock=368,
        redline_rpm=8200,
        idle_rpm=900,
        boost_psi_stock=12.0,
        compression_ratio=8.5,
        firing_order="1-5-3-6-2-4",
        horsepower_potential=1000,
        torque_potential_nm=1000,
        cooling_requirement_kw=35,
        oil_capacity_liters=5.2,
        notes="High-revving character. NISMO N1 block recommended for power >600hp. Water and oil cooler mandatory at high power.",
    ),

    Engine(
        id="chevy_ls3",
        name="Chevrolet LS3 6.2L",
        brand="General Motors",
        category=PartCategory.ENGINE,
        description="6.2L OHV V8 from the C6 Corvette. Compact for its displacement, incredibly swap-friendly. Pushrod simplicity with massive torque.",
        dimensions=Dimensions(length_mm=565, width_mm=550, height_mm=640),
        weight_kg=204,
        price_usd=8500,
        displacement_cc=6162,
        cylinder_count=8,
        cylinder_config=CylinderConfig.V8,
        aspiration=AspirationMode.NA,
        fuel_type="Gasoline / E85",
        horsepower_stock=436,
        torque_nm_stock=595,
        redline_rpm=6600,
        idle_rpm=700,
        compression_ratio=10.7,
        firing_order="1-8-7-2-6-5-4-3",
        horsepower_potential=700,
        torque_potential_nm=900,
        cooling_requirement_kw=32,
        oil_capacity_liters=6.0,
        notes="Most popular V8 swap base. Enormous aftermarket. Front-sump oil pan swap required for many chassis.",
    ),

    Engine(
        id="chevy_ls7",
        name="Chevrolet LS7 7.0L",
        brand="General Motors",
        category=PartCategory.ENGINE,
        description="7.0L naturally aspirated V8 from the Z06 Corvette. Titanium rods, dry-sump, flat-plane-adjacent firing — screams to 7100 rpm. Highest-revving LS.",
        dimensions=Dimensions(length_mm=570, width_mm=556, height_mm=645),
        weight_kg=204,
        price_usd=14000,
        displacement_cc=7011,
        cylinder_count=8,
        cylinder_config=CylinderConfig.V8,
        aspiration=AspirationMode.NA,
        fuel_type="Gasoline",
        horsepower_stock=505,
        torque_nm_stock=637,
        redline_rpm=7100,
        idle_rpm=700,
        compression_ratio=11.0,
        firing_order="1-8-7-2-6-5-4-3",
        horsepower_potential=850,
        torque_potential_nm=950,
        cooling_requirement_kw=38,
        oil_capacity_liters=8.0,
        notes="Dry-sump only. Titanium connecting rods—do not rev with low oil. LS7 heads on LS3 block is popular.",
    ),

    Engine(
        id="honda_k20a",
        name="Honda K20A Type R",
        brand="Honda",
        category=PartCategory.ENGINE,
        description="2.0L naturally aspirated DOHC i-VTEC from the EP3/DC5 Type R. High-revving gem with 8400 rpm redline. Beloved for lightweight and handling builds.",
        dimensions=Dimensions(length_mm=420, width_mm=560, height_mm=620),
        weight_kg=148,
        price_usd=4200,
        displacement_cc=1998,
        cylinder_count=4,
        cylinder_config=CylinderConfig.I4,
        aspiration=AspirationMode.NA,
        fuel_type="Gasoline",
        horsepower_stock=215,
        torque_nm_stock=215,
        redline_rpm=8400,
        idle_rpm=800,
        compression_ratio=11.5,
        firing_order="1-3-4-2",
        horsepower_potential=450,
        torque_potential_nm=500,
        cooling_requirement_kw=18,
        oil_capacity_liters=4.2,
        notes="Extremely light. Perfect for lightweight track builds. K-series swap kits exist for many chassis.",
    ),

    Engine(
        id="mazda_13b_rew",
        name="Mazda 13B-REW",
        brand="Mazda",
        category=PartCategory.ENGINE,
        description="1.3L twin-rotor Wankel rotary twin-turbo from the FD RX-7. Sequential twin turbos. Incredibly compact and light. Unique maintenance demands.",
        dimensions=Dimensions(length_mm=450, width_mm=430, height_mm=510),
        weight_kg=108,
        price_usd=6500,
        displacement_cc=1308,
        cylinder_count=2,
        cylinder_config=CylinderConfig.ROTARY,
        aspiration=AspirationMode.TWIN_TURBO,
        fuel_type="Gasoline / Rich premix",
        horsepower_stock=255,
        torque_nm_stock=294,
        redline_rpm=8000,
        idle_rpm=900,
        boost_psi_stock=9.0,
        compression_ratio=9.0,
        firing_order="Sequential rotor",
        horsepower_potential=700,
        torque_potential_nm=700,
        cooling_requirement_kw=30,
        oil_capacity_liters=4.0,
        notes="Apex seals must be monitored. Runs rich by design. Extremely light swap candidate. Apex Racing engines available.",
    ),

    Engine(
        id="subaru_ej207",
        name="Subaru EJ207 STI",
        brand="Subaru",
        category=PartCategory.ENGINE,
        description="2.0L flat-four turbo from the GC/GD/GR STI. Distinctive boxer rumble, low center of gravity. AWD-optimized packaging.",
        dimensions=Dimensions(length_mm=510, width_mm=620, height_mm=500),
        weight_kg=188,
        price_usd=5500,
        displacement_cc=1994,
        cylinder_count=4,
        cylinder_config=CylinderConfig.H4,
        aspiration=AspirationMode.TURBO,
        fuel_type="Gasoline / E85",
        horsepower_stock=280,
        torque_nm_stock=392,
        redline_rpm=7500,
        idle_rpm=850,
        boost_psi_stock=14.5,
        compression_ratio=8.2,
        firing_order="1-3-2-4",
        horsepower_potential=600,
        torque_potential_nm=700,
        cooling_requirement_kw=28,
        oil_capacity_liters=4.5,
        notes="EJ20 / EJ25 family. Phase 2 vs Phase 1 heads matter. EJ257 is the 2.5L variant with more torque.",
    ),

    Engine(
        id="ford_coyote_5",
        name="Ford 5.0 Coyote Gen 3",
        brand="Ford",
        category=PartCategory.ENGINE,
        description="5.0L DOHC V8 from the S550 Mustang GT. Ti-VCT on all four cams. Excellent aftermarket, modular family makes parts plentiful.",
        dimensions=Dimensions(length_mm=590, width_mm=590, height_mm=650),
        weight_kg=214,
        price_usd=9000,
        displacement_cc=4951,
        cylinder_count=8,
        cylinder_config=CylinderConfig.V8,
        aspiration=AspirationMode.NA,
        fuel_type="Gasoline / E85",
        horsepower_stock=460,
        torque_nm_stock=529,
        redline_rpm=7600,
        idle_rpm=650,
        compression_ratio=12.0,
        firing_order="1-5-4-8-6-3-7-2",
        horsepower_potential=800,
        torque_potential_nm=950,
        cooling_requirement_kw=35,
        oil_capacity_liters=8.8,
        notes="Cross-plane V8 with great sound. Gen 3 adds port + direct injection. High-revving for a V8.",
    ),

    Engine(
        id="dodge_hellcat",
        name="Dodge Hellcat 6.2L Supercharged",
        brand="Chrysler / Dodge",
        category=PartCategory.ENGINE,
        description="6.2L HEMI V8 with IHI twin-screw supercharger. 2.4L positive displacement blower. 707 hp stock — 797 in Redeye form.",
        dimensions=Dimensions(length_mm=660, width_mm=750, height_mm=820),
        weight_kg=280,
        price_usd=22000,
        displacement_cc=6166,
        cylinder_count=8,
        cylinder_config=CylinderConfig.V8,
        aspiration=AspirationMode.SUPER,
        fuel_type="Gasoline / E85",
        horsepower_stock=707,
        torque_nm_stock=881,
        redline_rpm=6200,
        idle_rpm=750,
        boost_psi_stock=11.6,
        compression_ratio=9.5,
        firing_order="1-8-4-3-6-5-7-2",
        horsepower_potential=1200,
        torque_potential_nm=1400,
        cooling_requirement_kw=60,
        oil_capacity_liters=7.6,
        notes="Very wide supercharger raises hood clearance requirements. Heavy but brutally torquey. Popular in muscle car builds.",
        requires_fabrication=True,
        fabrication_difficulty=7,
    ),

    Engine(
        id="lamborghini_lp700_v12",
        name="Lamborghini 6.5L V12 LP700",
        brand="Lamborghini",
        category=PartCategory.ENGINE,
        description="6.5L naturally aspirated V12 from the Aventador LP700-4. 8500 rpm redline. ISR transmission integrated — standalone fitment requires full fabrication.",
        dimensions=Dimensions(length_mm=650, width_mm=700, height_mm=560),
        weight_kg=285,
        price_usd=95000,
        displacement_cc=6498,
        cylinder_count=12,
        cylinder_config=CylinderConfig.V12,
        aspiration=AspirationMode.NA,
        fuel_type="Gasoline",
        horsepower_stock=700,
        torque_nm_stock=690,
        redline_rpm=8500,
        idle_rpm=900,
        compression_ratio=11.8,
        firing_order="1-7-5-11-3-9-6-12-2-8-4-10",
        horsepower_potential=900,
        torque_potential_nm=850,
        cooling_requirement_kw=75,
        oil_capacity_liters=10.0,
        notes="Extreme project. Integrated ISR transmission must be removed or adapted. Massive cooling requirement. Legendary sound.",
        requires_fabrication=True,
        fabrication_difficulty=10,
    ),

    Engine(
        id="bmw_s85_v10",
        name="BMW S85 5.0L V10",
        brand="BMW M",
        category=PartCategory.ENGINE,
        description="5.0L naturally aspirated V10 from the E60 M5 / E63 M6. F1-inspired flat-plane crank. 8250 rpm redline. One of the greatest sounding engines ever made.",
        dimensions=Dimensions(length_mm=620, width_mm=680, height_mm=620),
        weight_kg=226,
        price_usd=18000,
        displacement_cc=4999,
        cylinder_count=10,
        cylinder_config=CylinderConfig.V10,
        aspiration=AspirationMode.NA,
        fuel_type="Gasoline",
        horsepower_stock=507,
        torque_nm_stock=520,
        redline_rpm=8250,
        idle_rpm=800,
        compression_ratio=12.0,
        firing_order="1-6-5-10-2-7-3-8-4-9",
        horsepower_potential=700,
        torque_potential_nm=700,
        cooling_requirement_kw=45,
        oil_capacity_liters=8.5,
        notes="High-strung NA unit. Rod bearing interval at 60k miles is critical. SMG II gearbox integration complex.",
    ),

    Engine(
        id="honda_k24",
        name="Honda K24A / K24Z7",
        brand="Honda",
        category=PartCategory.ENGINE,
        description="2.4L naturally aspirated DOHC i-VTEC. Longer stroke than K20 gives more torque. Popular base for forced-induction K-builds. 11,000 rpm possible with built motor.",
        dimensions=Dimensions(length_mm=430, width_mm=560, height_mm=625),
        weight_kg=155,
        price_usd=3000,
        displacement_cc=2354,
        cylinder_count=4,
        cylinder_config=CylinderConfig.I4,
        aspiration=AspirationMode.NA,
        fuel_type="Gasoline / E85",
        horsepower_stock=201,
        torque_nm_stock=225,
        redline_rpm=7100,
        idle_rpm=750,
        compression_ratio=11.0,
        firing_order="1-3-4-2",
        horsepower_potential=600,
        torque_potential_nm=650,
        cooling_requirement_kw=20,
        oil_capacity_liters=4.4,
        notes="K24 block + K20 head (K24Z / K20A2 hybrid) is the ideal combo. Excellent budget swap engine.",
    ),

    Engine(
        id="toyota_1jz_gte",
        name="Toyota 1JZ-GTE",
        brand="Toyota",
        category=PartCategory.ENGINE,
        description="2.5L twin-turbo inline-six — the compact sibling of the 2JZ. Common in JZX100 Chaser / Cresta. Popular in drift and touring car builds.",
        dimensions=Dimensions(length_mm=580, width_mm=530, height_mm=680),
        weight_kg=210,
        price_usd=5500,
        displacement_cc=2492,
        cylinder_count=6,
        cylinder_config=CylinderConfig.I6,
        aspiration=AspirationMode.TWIN_TURBO,
        fuel_type="Gasoline / E85",
        horsepower_stock=280,
        torque_nm_stock=363,
        redline_rpm=7200,
        idle_rpm=800,
        boost_psi_stock=9.0,
        compression_ratio=8.5,
        firing_order="1-5-3-6-2-4",
        horsepower_potential=800,
        torque_potential_nm=900,
        cooling_requirement_kw=30,
        oil_capacity_liters=5.0,
        notes="VVT-i (VVTI) version preferred. Similar wiring to 2JZ makes swaps easier.",
    ),

    Engine(
        id="nissan_sr20det",
        name="Nissan SR20DET Red-Top",
        brand="Nissan",
        category=PartCategory.ENGINE,
        description="2.0L DOHC turbocharged inline-four from the S13/S14 Silvia. The quintessential drift engine. T25 turbo stock, big single potential.",
        dimensions=Dimensions(length_mm=450, width_mm=510, height_mm=600),
        weight_kg=148,
        price_usd=3800,
        displacement_cc=1998,
        cylinder_count=4,
        cylinder_config=CylinderConfig.I4,
        aspiration=AspirationMode.TURBO,
        fuel_type="Gasoline / E85",
        horsepower_stock=205,
        torque_nm_stock=275,
        redline_rpm=7500,
        idle_rpm=900,
        boost_psi_stock=8.7,
        compression_ratio=8.5,
        firing_order="1-3-4-2",
        horsepower_potential=500,
        torque_potential_nm=550,
        cooling_requirement_kw=22,
        oil_capacity_liters=3.8,
        notes="Red-top is most desirable. Lightweight package. Perfect for S-chassis or AE86 swaps.",
    ),

    Engine(
        id="mitsubishi_4g63t",
        name="Mitsubishi 4G63T Evo IX",
        brand="Mitsubishi",
        category=PartCategory.ENGINE,
        description="2.0L DOHC turbocharged inline-four from the Lancer Evolution. Iron block / aluminum head. MIVEC cam phasing in later versions. Rally-proven.",
        dimensions=Dimensions(length_mm=430, width_mm=500, height_mm=590),
        weight_kg=155,
        price_usd=4500,
        displacement_cc=1997,
        cylinder_count=4,
        cylinder_config=CylinderConfig.I4,
        aspiration=AspirationMode.TURBO,
        fuel_type="Gasoline / E85",
        horsepower_stock=286,
        torque_nm_stock=400,
        redline_rpm=7000,
        idle_rpm=850,
        boost_psi_stock=16.0,
        compression_ratio=8.8,
        firing_order="1-3-4-2",
        horsepower_potential=700,
        torque_potential_nm=800,
        cooling_requirement_kw=28,
        oil_capacity_liters=4.7,
        notes="Extremely strong iron block. EVO IX MIVEC head flows well. AWD-optimized but popular in RWD conversions.",
    ),

    Engine(
        id="toyota_3sgte",
        name="Toyota 3S-GTE Gen 4",
        brand="Toyota",
        category=PartCategory.ENGINE,
        description="2.0L DOHC turbocharged inline-four from the ST205 Celica GT-Four and MR2 Turbo. Gen 4 is the best flowing variant.",
        dimensions=Dimensions(length_mm=420, width_mm=510, height_mm=590),
        weight_kg=158,
        price_usd=3200,
        displacement_cc=1998,
        cylinder_count=4,
        cylinder_config=CylinderConfig.I4,
        aspiration=AspirationMode.TURBO,
        fuel_type="Gasoline / E85",
        horsepower_stock=245,
        torque_nm_stock=304,
        redline_rpm=7200,
        idle_rpm=850,
        boost_psi_stock=12.0,
        compression_ratio=8.5,
        firing_order="1-3-4-2",
        horsepower_potential=550,
        torque_potential_nm=600,
        cooling_requirement_kw=25,
        oil_capacity_liters=4.0,
        notes="Perfect for SW20 MR2 or ST205 builds. Mid-engine fitment-friendly due to compact dimensions.",
    ),

    Engine(
        id="tesla_dual_motor",
        name="Tesla Dual Motor (Model 3 Performance)",
        brand="Tesla",
        category=PartCategory.ENGINE,
        description="Dual permanent magnet AC motor setup from Model 3 Performance. Rear motor: 375V AC induction. Instant torque, no gearbox needed. AWD-native.",
        dimensions=Dimensions(length_mm=400, width_mm=350, height_mm=350),
        weight_kg=130,
        price_usd=15000,
        displacement_cc=0,
        cylinder_count=0,
        cylinder_config=CylinderConfig.ELECTRIC,
        aspiration=AspirationMode.ELECTRIC,
        fuel_type="Electric",
        horsepower_stock=450,
        torque_nm_stock=650,
        redline_rpm=18000,
        idle_rpm=0,
        compression_ratio=1.0,
        firing_order="N/A",
        horsepower_potential=600,
        torque_potential_nm=900,
        cooling_requirement_kw=25,
        oil_capacity_liters=0,
        notes="Requires 400V battery pack (not included). No clutch or transmission needed. Inverter is included. OTA tune possible.",
        requires_fabrication=True,
        fabrication_difficulty=8,
    ),

    Engine(
        id="suzuki_hayabusa_i4",
        name="Suzuki Hayabusa 1340cc",
        brand="Suzuki",
        category=PartCategory.ENGINE,
        description="1.3L inline-four motorcycle engine. Insane power-to-weight ratio. Popular in locost / track day specials. Requires custom adapter and sequential box.",
        dimensions=Dimensions(length_mm=400, width_mm=380, height_mm=480),
        weight_kg=72,
        price_usd=3500,
        displacement_cc=1340,
        cylinder_count=4,
        cylinder_config=CylinderConfig.I4,
        aspiration=AspirationMode.NA,
        fuel_type="Gasoline",
        horsepower_stock=197,
        torque_nm_stock=155,
        redline_rpm=11000,
        idle_rpm=1200,
        compression_ratio=12.5,
        firing_order="1-2-4-3",
        horsepower_potential=300,
        torque_potential_nm=300,
        cooling_requirement_kw=15,
        oil_capacity_liters=3.7,
        notes="Requires custom engine cradle and sequential gearbox adapter. No reverse gear — must add separate reverse mechanism.",
        requires_fabrication=True,
        fabrication_difficulty=9,
    ),

    Engine(
        id="porsche_9a1_gt3",
        name="Porsche 9A1 4.0L GT3",
        brand="Porsche",
        category=PartCategory.ENGINE,
        description="4.0L naturally aspirated flat-six from the 992 GT3. 9000 rpm, titanium con rods, dry sump. One of the greatest road car engines ever built.",
        dimensions=Dimensions(length_mm=620, width_mm=680, height_mm=540),
        weight_kg=202,
        price_usd=45000,
        displacement_cc=3996,
        cylinder_count=6,
        cylinder_config=CylinderConfig.H6,
        aspiration=AspirationMode.NA,
        fuel_type="Gasoline / E50",
        horsepower_stock=510,
        torque_nm_stock=470,
        redline_rpm=9000,
        idle_rpm=800,
        compression_ratio=13.3,
        firing_order="1-6-2-4-3-5",
        horsepower_potential=650,
        torque_potential_nm=600,
        cooling_requirement_kw=42,
        oil_capacity_liters=9.5,
        notes="Dry-sump mandatory. Wide flat-six packaging has very specific clearance needs. PDK or manual adaptation required.",
        requires_fabrication=True,
        fabrication_difficulty=9,
    ),

    Engine(
        id="ls_lsx454r",
        name="Chevrolet LSX454R Crate",
        brand="GM Performance",
        category=PartCategory.ENGINE,
        description="7.4L purpose-built crate LS race engine from GM Performance. Cast-iron LSX block, ported LS7 heads. 776 hp out of the box. Race-ready.",
        dimensions=Dimensions(length_mm=575, width_mm=565, height_mm=660),
        weight_kg=240,
        price_usd=19500,
        displacement_cc=7440,
        cylinder_count=8,
        cylinder_config=CylinderConfig.V8,
        aspiration=AspirationMode.NA,
        fuel_type="Gasoline / E85 / Methanol",
        horsepower_stock=776,
        torque_nm_stock=915,
        redline_rpm=7000,
        idle_rpm=800,
        compression_ratio=12.0,
        firing_order="1-8-7-2-6-5-4-3",
        horsepower_potential=1200,
        torque_potential_nm=1400,
        cooling_requirement_kw=65,
        oil_capacity_liters=8.0,
        notes="Race engine — no smog equipment. Requires standalone ECU (e.g., Holley Dominator). Enormous torque from idle.",
    ),

    Engine(
        id="ford_7_3_godzilla",
        name="Ford 7.3L Godzilla V8",
        brand="Ford",
        category=PartCategory.ENGINE,
        description="7.3L DOHC pushrod V8 from the Super Duty F-Series. Massive low-end torque. Port injection + direct injection. Underrated performance potential.",
        dimensions=Dimensions(length_mm=625, width_mm=640, height_mm=720),
        weight_kg=308,
        price_usd=9000,
        displacement_cc=7335,
        cylinder_count=8,
        cylinder_config=CylinderConfig.V8,
        aspiration=AspirationMode.NA,
        fuel_type="Gasoline / E85",
        horsepower_stock=445,
        torque_nm_stock=637,
        redline_rpm=6500,
        idle_rpm=650,
        compression_ratio=10.5,
        firing_order="1-5-4-8-6-3-7-2",
        horsepower_potential=900,
        torque_potential_nm=1100,
        cooling_requirement_kw=55,
        oil_capacity_liters=10.0,
        notes="Very heavy — best in large chassis. Requires custom front-sump oil pan and headers for most swaps.",
        requires_fabrication=True,
        fabrication_difficulty=6,
    ),

    Engine(
        id="bmw_s54",
        name="BMW S54 3.2L",
        brand="BMW M",
        category=PartCategory.ENGINE,
        description="3.2L naturally aspirated DOHC inline-six from the E46 M3. Individual throttle bodies (ITB), 8000 rpm, 338 hp. Last of the great NA M-engines before turbo era.",
        dimensions=Dimensions(length_mm=610, width_mm=580, height_mm=600),
        weight_kg=185,
        price_usd=12000,
        displacement_cc=3246,
        cylinder_count=6,
        cylinder_config=CylinderConfig.I6,
        aspiration=AspirationMode.NA,
        fuel_type="Gasoline",
        horsepower_stock=338,
        torque_nm_stock=365,
        redline_rpm=8000,
        idle_rpm=800,
        compression_ratio=11.5,
        firing_order="1-5-3-6-2-4",
        horsepower_potential=500,
        torque_potential_nm=500,
        cooling_requirement_kw=30,
        oil_capacity_liters=6.0,
        notes="ITBs require specific airbox or velocity stacks. Subframe swap needed for non-BMW fitment. Rod bearings are wear item.",
    ),

    Engine(
        id="ferrari_458_v8",
        name="Ferrari 458 4.5L V8",
        brand="Ferrari",
        category=PartCategory.ENGINE,
        description="4.5L naturally aspirated flat-plane V8. 9000 rpm redline, 570 hp. One of the greatest sounding road car engines ever made. F1-derived technology.",
        dimensions=Dimensions(length_mm=580, width_mm=650, height_mm=540),
        weight_kg=185,
        price_usd=75000,
        displacement_cc=4497,
        cylinder_count=8,
        cylinder_config=CylinderConfig.V8,
        aspiration=AspirationMode.NA,
        fuel_type="Gasoline",
        horsepower_stock=570,
        torque_nm_stock=540,
        redline_rpm=9000,
        idle_rpm=950,
        compression_ratio=12.5,
        firing_order="1-5-3-7-4-8-2-6",
        horsepower_potential=700,
        torque_potential_nm=650,
        cooling_requirement_kw=55,
        oil_capacity_liters=9.0,
        notes="Flat-plane V8 — signature exhaust note. Designed for mid-engine transaxle layout. Fitment in FR chassis requires significant custom work.",
        requires_fabrication=True,
        fabrication_difficulty=9,
    ),
]


# ═══════════════════════════════════════════════════════════════
#  CHASSIS  (12 platforms)
# ═══════════════════════════════════════════════════════════════

CHASSIS_LIST: list[Chassis] = [

    Chassis(
        id="nissan_s15",
        name="Nissan Silvia S15",
        manufacturer="Nissan",
        year_range="1999–2002",
        drivetrain_stock=DrivetrainType.FR,
        engine_bay=EngineBay(
            length_mm=750, width_mm=820, height_mm=680,
            firewall_setback_mm=120, subframe_width_mm=590,
            has_crossmember=True,
        ),
        wheelbase_mm=2525,
        front_track_mm=1480,
        rear_track_mm=1460,
        curb_weight_kg=1190,
        weight_dist_front=0.58,
        stock_engine_id="nissan_sr20det",
        stock_transmission="Aisin FS5W71C 5-speed",
        max_engine_weight_kg=280,
        price_usd=18000,
        description="Iconic Japanese FR sports car. Exceptional balance, drift pedigree, enormous aftermarket. The perfect swap platform.",
    ),

    Chassis(
        id="toyota_supra_a80",
        name="Toyota Supra A80 (JZA80)",
        manufacturer="Toyota",
        year_range="1993–2002",
        drivetrain_stock=DrivetrainType.FR,
        engine_bay=EngineBay(
            length_mm=820, width_mm=860, height_mm=700,
            firewall_setback_mm=140, subframe_width_mm=620,
            has_crossmember=True,
        ),
        wheelbase_mm=2550,
        front_track_mm=1490,
        rear_track_mm=1510,
        curb_weight_kg=1580,
        weight_dist_front=0.54,
        stock_engine_id="toyota_2jz_gte",
        stock_transmission="Getrag V160 6-speed",
        max_engine_weight_kg=320,
        price_usd=65000,
        description="The legendary twin-turbo icon. Wide engine bay fits most inline-six and even compact V8 swaps. Rigid chassis, excellent aero potential.",
    ),

    Chassis(
        id="mazda_rx7_fd",
        name="Mazda RX-7 FD3S",
        manufacturer="Mazda",
        year_range="1992–2002",
        drivetrain_stock=DrivetrainType.FR,
        engine_bay=EngineBay(
            length_mm=640, width_mm=740, height_mm=620,
            firewall_setback_mm=90, subframe_width_mm=540,
            has_crossmember=True,
        ),
        wheelbase_mm=2425,
        front_track_mm=1450,
        rear_track_mm=1460,
        curb_weight_kg=1280,
        weight_dist_front=0.51,
        stock_engine_id="mazda_13b_rew",
        stock_transmission="Mazda 5-speed CD009",
        max_engine_weight_kg=230,
        price_usd=35000,
        description="The benchmark for chassis balance. Small engine bay makes swaps challenging — short engines preferred. 50/50 weight distribution. Pop-up headlights.",
    ),

    Chassis(
        id="bmw_e46_m3",
        name="BMW E46 M3",
        manufacturer="BMW",
        year_range="2001–2006",
        drivetrain_stock=DrivetrainType.FR,
        engine_bay=EngineBay(
            length_mm=790, width_mm=840, height_mm=680,
            firewall_setback_mm=130, subframe_width_mm=600,
            has_crossmember=True,
        ),
        wheelbase_mm=2730,
        front_track_mm=1500,
        rear_track_mm=1515,
        curb_weight_kg=1570,
        weight_dist_front=0.52,
        stock_engine_id="bmw_s54",
        stock_transmission="Getrag 420G 6-speed",
        max_engine_weight_kg=280,
        price_usd=35000,
        description="German precision FR platform. Excellent suspension geometry, ZCP options. LS-swap kits exist. Strong subframe. Track-capable out of the box.",
    ),

    Chassis(
        id="honda_s2000_ap1",
        name="Honda S2000 AP1/AP2",
        manufacturer="Honda",
        year_range="1999–2009",
        drivetrain_stock=DrivetrainType.FR,
        engine_bay=EngineBay(
            length_mm=680, width_mm=760, height_mm=620,
            firewall_setback_mm=100, subframe_width_mm=540,
            has_crossmember=True,
        ),
        wheelbase_mm=2400,
        front_track_mm=1470,
        rear_track_mm=1530,
        curb_weight_kg=1270,
        weight_dist_front=0.48,
        stock_engine_id="honda_k20a",
        stock_transmission="Aisin AZ-6 6-speed",
        max_engine_weight_kg=220,
        price_usd=30000,
        description="Precision-engineered lightweight roadster. Mid-front engine placement, 50/50 balance. Tight engine bay — compact engines only. Exceptional chassis.",
    ),

    Chassis(
        id="subaru_gc8_sti",
        name="Subaru Impreza GC8 STI",
        manufacturer="Subaru",
        year_range="1992–2000",
        drivetrain_stock=DrivetrainType.AWD,
        engine_bay=EngineBay(
            length_mm=700, width_mm=840, height_mm=580,
            firewall_setback_mm=110, subframe_width_mm=590,
            has_crossmember=True,
        ),
        wheelbase_mm=2520,
        front_track_mm=1450,
        rear_track_mm=1460,
        curb_weight_kg=1300,
        weight_dist_front=0.60,
        stock_engine_id="subaru_ej207",
        stock_transmission="STI 5-speed close ratio",
        max_engine_weight_kg=240,
        price_usd=22000,
        description="Rally-bred AWD platform. Wide track, low boxer center of gravity. Classic 'bug-eye' look. EJ-family swap is straightforward; others require AWD system modification.",
    ),

    Chassis(
        id="mitsubishi_evo9",
        name="Mitsubishi Lancer Evolution IX",
        manufacturer="Mitsubishi",
        year_range="2005–2007",
        drivetrain_stock=DrivetrainType.AWD,
        engine_bay=EngineBay(
            length_mm=690, width_mm=830, height_mm=590,
            firewall_setback_mm=115, subframe_width_mm=580,
            has_crossmember=True,
        ),
        wheelbase_mm=2625,
        front_track_mm=1515,
        rear_track_mm=1530,
        curb_weight_kg=1410,
        weight_dist_front=0.61,
        stock_engine_id="mitsubishi_4g63t",
        stock_transmission="5-speed Getrag-sourced close ratio",
        max_engine_weight_kg=250,
        price_usd=28000,
        description="Super Lancer built for rally and track. Super AYC rear differential, ACD front. ACD AWD system is complex — engine swaps require full drivetrain overhaul.",
    ),

    Chassis(
        id="classic_mustang_1969",
        name="Ford Mustang 1969 Fastback",
        manufacturer="Ford",
        year_range="1969–1970",
        drivetrain_stock=DrivetrainType.FR,
        engine_bay=EngineBay(
            length_mm=930, width_mm=940, height_mm=780,
            firewall_setback_mm=180, subframe_width_mm=710,
            has_crossmember=False,
        ),
        wheelbase_mm=2745,
        front_track_mm=1550,
        rear_track_mm=1540,
        curb_weight_kg=1450,
        weight_dist_front=0.57,
        stock_engine_id="ford_coyote_5",
        stock_transmission="T56 6-speed",
        max_engine_weight_kg=400,
        price_usd=55000,
        description="Classic American muscle. Massive engine bay accommodates nearly anything. No crossmember — very swap-friendly. Leaf-spring rear (upgrade recommended). The icon.",
    ),

    Chassis(
        id="toyota_ae86",
        name="Toyota AE86 Trueno / Levin",
        manufacturer="Toyota",
        year_range="1983–1987",
        drivetrain_stock=DrivetrainType.FR,
        engine_bay=EngineBay(
            length_mm=700, width_mm=780, height_mm=630,
            firewall_setback_mm=85, subframe_width_mm=530,
            has_crossmember=True,
        ),
        wheelbase_mm=2400,
        front_track_mm=1365,
        rear_track_mm=1340,
        curb_weight_kg=940,
        weight_dist_front=0.55,
        stock_engine_id="toyota_3sgte",
        stock_transmission="Toyota T50 5-speed",
        max_engine_weight_kg=180,
        price_usd=30000,
        description="The Hachi-Roku. Ultra light, perfect balance, driven by Takumi Fujiwara. Small engine bay limits swap size. K-swap and SR20 are popular. Cult following.",
    ),

    Chassis(
        id="tube_frame_race",
        name="Custom Tube Frame Race Chassis",
        manufacturer="Custom Fabricated",
        year_range="Custom",
        drivetrain_stock=DrivetrainType.FR,
        engine_bay=EngineBay(
            length_mm=1000, width_mm=1000, height_mm=900,
            firewall_setback_mm=250, subframe_width_mm=800,
            has_crossmember=False,
        ),
        wheelbase_mm=2400,
        front_track_mm=1600,
        rear_track_mm=1600,
        curb_weight_kg=680,
        weight_dist_front=0.50,
        stock_engine_id="chevy_ls3",
        stock_transmission="T56 6-speed",
        max_engine_weight_kg=600,
        price_usd=28000,
        description="Start with a blank slate. Full custom tube frame with virtually no fitment constraints. Drivetrain is FR/AWD/MR configurable. For serious builds only.",
    ),

    Chassis(
        id="dodge_viper_gts",
        name="Dodge Viper GTS Gen II",
        manufacturer="Dodge",
        year_range="1996–2002",
        drivetrain_stock=DrivetrainType.FR,
        engine_bay=EngineBay(
            length_mm=1020, width_mm=950, height_mm=760,
            firewall_setback_mm=200, subframe_width_mm=720,
            has_crossmember=True,
        ),
        wheelbase_mm=2440,
        front_track_mm=1600,
        rear_track_mm=1610,
        curb_weight_kg=1550,
        weight_dist_front=0.49,
        stock_engine_id="dodge_hellcat",
        stock_transmission="Tremec T56 6-speed",
        max_engine_weight_kg=450,
        price_usd=80000,
        description="Raw, analog, brutal. Side exhaust exits make engine bay unique. V10 8.0L stock. Massive chassis capable of wild swaps. Significant room for a V12.",
    ),

    Chassis(
        id="vw_beetle_1967",
        name="Volkswagen Beetle 1967",
        manufacturer="Volkswagen",
        year_range="1965–1970",
        drivetrain_stock=DrivetrainType.RR,
        engine_bay=EngineBay(
            length_mm=620, width_mm=780, height_mm=520,
            firewall_setback_mm=60, subframe_width_mm=550,
            has_crossmember=False,
        ),
        wheelbase_mm=2400,
        front_track_mm=1305,
        rear_track_mm=1275,
        curb_weight_kg=840,
        weight_dist_front=0.42,
        stock_engine_id="honda_k20a",
        stock_transmission="VW 4-speed",
        max_engine_weight_kg=250,
        price_usd=12000,
        description="Air-cooled rear-engine classic. Mid/rear engine swap is natural. Subaru boxer or motorcycle engines are common. Unusual handling dynamics with rear engine weight.",
    ),
]


# ═══════════════════════════════════════════════════════════════
#  TURBOS  (10 units)
# ═══════════════════════════════════════════════════════════════

TURBOS: list[Turbo] = [

    Turbo(
        id="garrett_gt2860rs",
        name="Garrett GT2860RS",
        brand="Garrett",
        category=PartCategory.TURBO,
        description="Small, fast-spooling journal bearing turbo. Great street/track unit for 4-cylinder builds. GT-Series billet compressor wheel.",
        dimensions=Dimensions(length_mm=220, width_mm=180, height_mm=200),
        weight_kg=4.5,
        price_usd=1100,
        compressor_map="GT2860RS",
        max_boost_psi=25.0,
        spool_rpm=3200,
        max_flow_cfm=58,
        max_hp_support=400,
        journal_or_ball="Journal",
    ),

    Turbo(
        id="garrett_gt3582r",
        name="Garrett GT3582R",
        brand="Garrett",
        category=PartCategory.TURBO,
        description="Workhorse single turbo for inline-6 and small V8 builds. Ball-bearing center section, 82mm turbine wheel.",
        dimensions=Dimensions(length_mm=280, width_mm=240, height_mm=260),
        weight_kg=7.8,
        price_usd=1800,
        compressor_map="GT3582R",
        max_boost_psi=28.0,
        spool_rpm=3800,
        max_flow_cfm=85,
        max_hp_support=600,
        journal_or_ball="Ball",
    ),

    Turbo(
        id="garrett_g35_900",
        name="Garrett G35-900",
        brand="Garrett",
        category=PartCategory.TURBO,
        description="Garrett's G-Series unit with advanced aerodynamics. Dual ball bearing. 58mm inducer — extremely fast spool for its power level.",
        dimensions=Dimensions(length_mm=310, width_mm=265, height_mm=280),
        weight_kg=9.1,
        price_usd=2400,
        compressor_map="G35-900",
        max_boost_psi=35.0,
        spool_rpm=3500,
        max_flow_cfm=95,
        max_hp_support=900,
        anti_surge=True,
        journal_or_ball="Ball",
    ),

    Turbo(
        id="borgwarner_efr9180",
        name="BorgWarner EFR 9180",
        brand="BorgWarner",
        category=PartCategory.TURBO,
        description="EFR series with integrated wastegate and tial-style outlet. Maraging steel turbine wheel. Strong street/race option for V8 builds.",
        dimensions=Dimensions(length_mm=330, width_mm=290, height_mm=300),
        weight_kg=10.5,
        price_usd=2800,
        compressor_map="EFR9180",
        max_boost_psi=40.0,
        spool_rpm=4200,
        max_flow_cfm=105,
        max_hp_support=1050,
        anti_surge=True,
        journal_or_ball="Ball",
    ),

    Turbo(
        id="precision_6266",
        name="Precision Turbo 6266 CEA",
        brand="Precision Turbo",
        category=PartCategory.TURBO,
        description="Popular daily-driver-friendly turbo. CEA billet compressor wheel. Ball bearing. 550 hp support on 4-cylinders, great powerband.",
        dimensions=Dimensions(length_mm=270, width_mm=235, height_mm=250),
        weight_kg=7.2,
        price_usd=1400,
        compressor_map="6266 CEA",
        max_boost_psi=28.0,
        spool_rpm=3400,
        max_flow_cfm=78,
        max_hp_support=550,
        journal_or_ball="Ball",
    ),

    Turbo(
        id="precision_7675",
        name="Precision Turbo 7675 CEA",
        brand="Precision Turbo",
        category=PartCategory.TURBO,
        description="Big single for serious V8 builds. Ball bearing, 76mm inducer compressor. Paired with large intercooler mandatory.",
        dimensions=Dimensions(length_mm=360, width_mm=310, height_mm=340),
        weight_kg=13.5,
        price_usd=2100,
        compressor_map="7675 CEA",
        max_boost_psi=35.0,
        spool_rpm=4800,
        max_flow_cfm=120,
        max_hp_support=900,
        journal_or_ball="Ball",
    ),

    Turbo(
        id="twin_garrett_gt28",
        name="Twin Garrett GT28RS Kit",
        brand="Garrett",
        category=PartCategory.TURBO,
        description="Twin small turbo setup — parallel configuration. Faster spool than single large turbo, higher complexity. Common for inline-6 builds.",
        dimensions=Dimensions(length_mm=220, width_mm=180, height_mm=200),
        weight_kg=10.5,
        price_usd=2400,
        compressor_map="GT28RS x2",
        max_boost_psi=22.0,
        spool_rpm=2800,
        max_flow_cfm=116,
        max_hp_support=700,
        journal_or_ball="Journal",
    ),

    Turbo(
        id="holset_hx40",
        name="Holset HX40W",
        brand="Holset",
        category=PartCategory.TURBO,
        description="Heavy duty diesel-derived turbo repurposed for high HP builds. Budget option for compound or single applications. Very durable.",
        dimensions=Dimensions(length_mm=300, width_mm=260, height_mm=280),
        weight_kg=12.0,
        price_usd=600,
        compressor_map="HX40W",
        max_boost_psi=30.0,
        spool_rpm=4500,
        max_flow_cfm=90,
        max_hp_support=750,
        journal_or_ball="Journal",
    ),

    Turbo(
        id="borg_efr6758",
        name="BorgWarner EFR 6758",
        brand="BorgWarner",
        category=PartCategory.TURBO,
        description="Compact EFR with internal wastegate. Ideal for 4-cylinder builds where space is at a premium. Maraging steel turbine.",
        dimensions=Dimensions(length_mm=255, width_mm=215, height_mm=240),
        weight_kg=8.0,
        price_usd=2200,
        compressor_map="EFR6758",
        max_boost_psi=32.0,
        spool_rpm=3100,
        max_flow_cfm=75,
        max_hp_support=650,
        anti_surge=True,
        journal_or_ball="Ball",
    ),

    Turbo(
        id="gt45_t4_1050hp",
        name="GT45 T4 Flange 1050hp",
        brand="Generic / Budget",
        category=PartCategory.TURBO,
        description="Budget massive single turbo. Laggy, not ideal for street, but will support 1000+ hp on large-displacement engines. Common in drag builds.",
        dimensions=Dimensions(length_mm=390, width_mm=340, height_mm=370),
        weight_kg=17.0,
        price_usd=420,
        compressor_map="GT45 5862",
        max_boost_psi=40.0,
        spool_rpm=6000,
        max_flow_cfm=135,
        max_hp_support=1050,
        journal_or_ball="Journal",
    ),
]


# ═══════════════════════════════════════════════════════════════
#  TRANSMISSIONS  (8 gearboxes)
# ═══════════════════════════════════════════════════════════════

TRANSMISSIONS: list[Transmission] = [

    Transmission(
        id="tremec_t56_magnum",
        name="TREMEC T56 Magnum 6-Speed",
        brand="TREMEC",
        category=PartCategory.TRANSMISSION,
        description="The gold standard manual swap gearbox. Widely available, strong, and fits many tunnel configurations. Used in Viper, Camaro, Corvette.",
        dimensions=Dimensions(length_mm=610, width_mm=280, height_mm=260),
        weight_kg=54,
        price_usd=4200,
        gear_count=6,
        trans_type="Manual",
        max_torque_nm=1100,
        max_hp=900,
        gear_ratios=[2.66, 1.78, 1.30, 1.00, 0.80, 0.63],
        final_drive=3.42,
        compatible_engines=["chevy_ls3", "chevy_ls7", "ford_coyote_5", "dodge_hellcat"],
    ),

    Transmission(
        id="getrag_420g",
        name="Getrag 420G 6-Speed",
        brand="Getrag",
        category=PartCategory.TRANSMISSION,
        description="BMW's close-ratio 6-speed. OEM in M3/M5. Strong and well-designed. Shift quality is excellent. Preferred for BMW swaps.",
        dimensions=Dimensions(length_mm=595, width_mm=250, height_mm=240),
        weight_kg=42,
        price_usd=3000,
        gear_count=6,
        trans_type="Manual",
        max_torque_nm=600,
        max_hp=550,
        gear_ratios=[4.23, 2.53, 1.67, 1.23, 1.00, 0.83],
        final_drive=3.62,
        compatible_engines=["bmw_s54", "bmw_s58", "toyota_2jz_gte"],
    ),

    Transmission(
        id="aisin_v160",
        name="Aisin V160 6-Speed (Supra)",
        brand="Aisin",
        category=PartCategory.TRANSMISSION,
        description="The legendary W58 successor. Designed for 2JZ torque. Very popular for high-power 2JZ builds. Wide gear spread.",
        dimensions=Dimensions(length_mm=590, width_mm=265, height_mm=250),
        weight_kg=45,
        price_usd=3500,
        gear_count=6,
        trans_type="Manual",
        max_torque_nm=700,
        max_hp=650,
        gear_ratios=[3.83, 2.36, 1.68, 1.31, 1.00, 0.79],
        final_drive=3.21,
        compatible_engines=["toyota_2jz_gte", "toyota_1jz_gte", "nissan_rb26dett"],
    ),

    Transmission(
        id="dogbox_6spd_sequential",
        name="Samsonas ST6 Sequential 6-Speed",
        brand="Samsonas",
        category=PartCategory.TRANSMISSION,
        description="Full competition sequential dogbox. Straight-cut gears, no synchros. Instant shifts under load. Loud but devastatingly fast. Race only.",
        dimensions=Dimensions(length_mm=450, width_mm=240, height_mm=220),
        weight_kg=38,
        price_usd=8500,
        gear_count=6,
        trans_type="Sequential",
        max_torque_nm=1200,
        max_hp=1200,
        gear_ratios=[2.50, 1.84, 1.44, 1.17, 1.00, 0.87],
        final_drive=3.73,
        compatible_engines=[],  # universal adapter kits available
    ),

    Transmission(
        id="tremec_tr6060",
        name="TREMEC TR-6060 6-Speed",
        brand="TREMEC",
        category=PartCategory.TRANSMISSION,
        description="High-performance manual from Z/28 Camaro and BOSS 302. Deeper overdrive than T56. GT500 and Z06 spec versions available.",
        dimensions=Dimensions(length_mm=600, width_mm=265, height_mm=255),
        weight_kg=52,
        price_usd=3800,
        gear_count=6,
        trans_type="Manual",
        max_torque_nm=900,
        max_hp=750,
        gear_ratios=[2.97, 2.07, 1.43, 1.00, 0.84, 0.63],
        final_drive=3.45,
        compatible_engines=["chevy_ls3", "chevy_ls7", "ford_coyote_5"],
    ),

    Transmission(
        id="zf_8hp90",
        name="ZF 8HP90 8-Speed Auto",
        brand="ZF",
        category=PartCategory.TRANSMISSION,
        description="ZF's brilliant 8-speed used in everything from BMW to RAM. Extremely adaptable, quick shift paddles. Popular for high-HP automatic builds.",
        dimensions=Dimensions(length_mm=640, width_mm=305, height_mm=295),
        weight_kg=84,
        price_usd=5200,
        gear_count=8,
        trans_type="Auto",
        max_torque_nm=900,
        max_hp=850,
        gear_ratios=[4.71, 3.14, 2.11, 1.67, 1.28, 1.00, 0.84, 0.67],
        final_drive=3.15,
        compatible_engines=["bmw_s58", "chevy_ls3", "ford_coyote_5", "dodge_hellcat"],
    ),

    Transmission(
        id="cd009_nissan",
        name="Nissan CD009 6-Speed (350Z/G35)",
        brand="Nissan",
        category=PartCategory.TRANSMISSION,
        description="Popular drift-spec 6-speed gearbox. Strong, widely available, cost-effective. Popular with SR20 and RB-series swaps. Known for reliable ratios.",
        dimensions=Dimensions(length_mm=580, width_mm=250, height_mm=240),
        weight_kg=43,
        price_usd=1800,
        gear_count=6,
        trans_type="Manual",
        max_torque_nm=600,
        max_hp=500,
        gear_ratios=[3.79, 2.32, 1.65, 1.29, 1.00, 0.79],
        final_drive=3.70,
        compatible_engines=["nissan_sr20det", "toyota_2jz_gte", "nissan_rb26dett"],
    ),

    Transmission(
        id="paddle_6spd_sequential",
        name="Xtrac 6-Speed Sequential Paddle",
        brand="Xtrac",
        category=PartCategory.TRANSMISSION,
        description="Full paddle-shift sequential used in GT3, GT4, and touring car racing. Hydraulic actuation, lightning-fast shifts. Not street-legal in many regions.",
        dimensions=Dimensions(length_mm=420, width_mm=235, height_mm=210),
        weight_kg=35,
        price_usd=18000,
        gear_count=6,
        trans_type="Sequential",
        max_torque_nm=1000,
        max_hp=1000,
        gear_ratios=[2.40, 1.80, 1.44, 1.17, 1.00, 0.88],
        final_drive=3.90,
        compatible_engines=[],
    ),
]


# ═══════════════════════════════════════════════════════════════
#  ECUs  (6 units)
# ═══════════════════════════════════════════════════════════════

ECUS: list[ECU] = [

    ECU(
        id="haltech_elite_2500",
        name="Haltech Elite 2500 Standalone",
        brand="Haltech",
        category=PartCategory.ECU,
        description="Full-featured standalone ECU. Supports up to 12 cylinders, E-throttle, flex-fuel, launch control, ABS integration. Industry standard for serious builds.",
        dimensions=Dimensions(length_mm=220, width_mm=165, height_mm=50),
        weight_kg=0.8,
        price_usd=2500,
        ecu_type="Standalone",
        max_injector_cc=2500,
        boost_control=True,
        launch_control=True,
        traction_control=True,
        flex_fuel=True,
        max_cylinders=12,
        tuning_software="Haltech NSP",
    ),

    ECU(
        id="link_g4x",
        name="Link G4X Xtreme Plugin",
        brand="Link",
        category=PartCategory.ECU,
        description="Popular ECU with model-specific plug-in versions. Traction control, DBW, 4D fuel/ignition maps. Great value for performance builds.",
        dimensions=Dimensions(length_mm=180, width_mm=140, height_mm=40),
        weight_kg=0.6,
        price_usd=1800,
        ecu_type="Standalone",
        max_injector_cc=2000,
        boost_control=True,
        launch_control=True,
        traction_control=True,
        flex_fuel=True,
        max_cylinders=8,
        tuning_software="PCLink",
    ),

    ECU(
        id="motec_m150",
        name="MoTeC M150 Race ECU",
        brand="MoTeC",
        category=PartCategory.ECU,
        description="Top-tier motorsport ECU used in GT3, IndyCar, WEC. Massive input/output count. Requires M1 Tune license per platform. The best money can buy.",
        dimensions=Dimensions(length_mm=230, width_mm=170, height_mm=55),
        weight_kg=1.1,
        price_usd=7200,
        ecu_type="Standalone",
        max_injector_cc=4000,
        boost_control=True,
        launch_control=True,
        traction_control=True,
        flex_fuel=True,
        max_cylinders=12,
        tuning_software="M1 Tune",
    ),

    ECU(
        id="holley_dominator",
        name="Holley Dominator EFI",
        brand="Holley",
        category=PartCategory.ECU,
        description="Purpose-built for LS/LT engines. Supports up to 16 injectors (E-85 builds), drive-by-wire, nitrous, boost control. Very popular for LS swaps.",
        dimensions=Dimensions(length_mm=200, width_mm=150, height_mm=45),
        weight_kg=0.7,
        price_usd=2200,
        ecu_type="Standalone",
        max_injector_cc=2200,
        boost_control=True,
        launch_control=True,
        traction_control=False,
        flex_fuel=True,
        max_cylinders=8,
        tuning_software="Holley EFI",
    ),

    ECU(
        id="ems_sprint_8",
        name="AEM Infinity 8 Standalone",
        brand="AEM",
        category=PartCategory.ECU,
        description="AEM's flagship standalone. UEGO wideband closed loop control built in. Popular for Honda/Subaru/Mitsubishi swaps. Windows-based tuning.",
        dimensions=Dimensions(length_mm=190, width_mm=135, height_mm=42),
        weight_kg=0.65,
        price_usd=1500,
        ecu_type="Standalone",
        max_injector_cc=1800,
        boost_control=True,
        launch_control=True,
        traction_control=True,
        flex_fuel=True,
        max_cylinders=8,
        tuning_software="AEM Infinity Tuner",
    ),

    ECU(
        id="piggyback_apexi_safc",
        name="APEXi SAFC II (Piggyback)",
        brand="APEXi",
        category=PartCategory.ECU,
        description="Classic piggyback fuel controller. Budget option — adjusts fuel trim signals. Not a full standalone. Compatible with most OEM ECUs for minor fueling mods.",
        dimensions=Dimensions(length_mm=130, width_mm=90, height_mm=25),
        weight_kg=0.2,
        price_usd=280,
        ecu_type="Piggyback",
        max_injector_cc=800,
        boost_control=False,
        launch_control=False,
        traction_control=False,
        flex_fuel=False,
        max_cylinders=8,
        tuning_software="APEXi SAFC II",
    ),
]


# ═══════════════════════════════════════════════════════════════
#  SUSPENSION  (5 kits)
# ═══════════════════════════════════════════════════════════════

SUSPENSION_KITS: list[SuspensionKit] = [

    SuspensionKit(
        id="bc_racing_br_coilovers",
        name="BC Racing BR Series Coilovers",
        brand="BC Racing",
        category=PartCategory.SUSPENSION,
        description="Popular entry-level performance coilover. 30-way damping adjustment, full height adjustment. Good street/track balance. Fits most Japanese sports cars.",
        dimensions=Dimensions(length_mm=450, width_mm=100, height_mm=100),
        weight_kg=10.0,
        price_usd=1200,
        suspension_type="Coilover",
        spring_rate_n_mm=8.0,
        damping_range="30 clicks",
        ride_height_range_mm="-30 to -80mm",
        camber_range_deg="-4.0° to 0°",
        caster_adjustable=False,
        toe_adjustable=True,
    ),

    SuspensionKit(
        id="ohlins_road_track",
        name="Öhlins Road & Track Coilovers",
        brand="Öhlins",
        category=PartCategory.SUSPENSION,
        description="Premium Swedish coilovers. TTX twin-tube continuous damping control. Used in GT3 racing. Exceptional handling balance. Adjustable on car.",
        dimensions=Dimensions(length_mm=480, width_mm=110, height_mm=110),
        weight_kg=12.5,
        price_usd=3800,
        suspension_type="Coilover",
        spring_rate_n_mm=15.0,
        damping_range="Continuous SDC",
        ride_height_range_mm="-20 to -70mm",
        camber_range_deg="-5.0° to +1°",
        caster_adjustable=True,
        toe_adjustable=True,
    ),

    SuspensionKit(
        id="air_lift_3h",
        name="Air Lift 3H Air Suspension",
        brand="Air Lift",
        category=PartCategory.SUSPENSION,
        description="Bolt-on air suspension. Height adjustable via air bags and controller. Variable stiffness. Popular for show car + street dual-purpose builds.",
        dimensions=Dimensions(length_mm=400, width_mm=200, height_mm=200),
        weight_kg=18.5,
        price_usd=2400,
        suspension_type="Air",
        spring_rate_n_mm=4.0,
        damping_range="Air pressure 40–200 PSI",
        ride_height_range_mm="-100 to +20mm",
        camber_range_deg="-3.5° to 0°",
        caster_adjustable=False,
        toe_adjustable=True,
    ),

    SuspensionKit(
        id="bilstein_pss10",
        name="Bilstein PSS10 Coilovers",
        brand="Bilstein",
        category=PartCategory.SUSPENSION,
        description="German-engineered 10-way adjustable. Monotube design. OEM-quality street manners with genuine track capability. Popular for GT86, BRZ, M3.",
        dimensions=Dimensions(length_mm=460, width_mm=105, height_mm=105),
        weight_kg=11.0,
        price_usd=2100,
        suspension_type="Coilover",
        spring_rate_n_mm=12.0,
        damping_range="10 clicks",
        ride_height_range_mm="-25 to -65mm",
        camber_range_deg="-3.0° to 0°",
        caster_adjustable=False,
        toe_adjustable=True,
    ),

    SuspensionKit(
        id="link_suspension_race",
        name="Custom Fabricated Race Linkage",
        brand="Custom",
        category=PartCategory.SUSPENSION,
        description="Fully custom multi-link rear / double-wishbone front. Maximum geometry adjustment. Race-only. Requires chassis fabrication and alignment rig.",
        dimensions=Dimensions(length_mm=500, width_mm=150, height_mm=150),
        weight_kg=14.0,
        price_usd=6000,
        suspension_type="Multi-link / Wishbone",
        spring_rate_n_mm=30.0,
        damping_range="Penske 8300 3-way adjustable",
        ride_height_range_mm="-10 to -120mm",
        camber_range_deg="-6.0° to +2°",
        caster_adjustable=True,
        toe_adjustable=True,
        requires_fabrication=True,
        fabrication_difficulty=8,
    ),
]


# ═══════════════════════════════════════════════════════════════
#  WHEELS  (5 options)
# ═══════════════════════════════════════════════════════════════

WHEELS: list[Wheel] = [
    Wheel(
        id="enkei_rpf1_17",
        name="Enkei RPF1 17x9",
        brand="Enkei",
        category=PartCategory.WHEELS,
        description="The benchmark lightweight track wheel. Flow-formed one-piece. Available in 15–18-inch. 5.97 kg per wheel.",
        dimensions=Dimensions(length_mm=229, width_mm=229, height_mm=430),
        weight_kg=5.97,
        price_usd=280,
        diameter_in=17,
        width_in=9,
        offset_mm=35,
        bolt_pattern="5x114.3",
        material="Flow-formed aluminum",
    ),
    Wheel(
        id="volk_te37sl_18",
        name="Rays Volk Racing TE37SL 18x10",
        brand="Rays",
        category=PartCategory.WHEELS,
        description="Legendary 6-spoke forged wheel. Ultra-light for its size. Track day weapon. Race heritage from JGTC/Super GT.",
        dimensions=Dimensions(length_mm=254, width_mm=254, height_mm=457),
        weight_kg=7.4,
        price_usd=700,
        diameter_in=18,
        width_in=10,
        offset_mm=25,
        bolt_pattern="5x114.3",
        material="Forged aluminum (6061-T6)",
    ),
    Wheel(
        id="bbs_ch_r_19",
        name="BBS CH-R 19x9.5",
        brand="BBS",
        category=PartCategory.WHEELS,
        description="German precision forged motorsport wheel. Multi-piece construction. Popular in DTM. Center-lock version available for race builds.",
        dimensions=Dimensions(length_mm=241, width_mm=241, height_mm=483),
        weight_kg=8.6,
        price_usd=850,
        diameter_in=19,
        width_in=9.5,
        offset_mm=30,
        bolt_pattern="5x120",
        material="Forged aluminum (3-piece)",
    ),
    Wheel(
        id="work_meister_s1_18",
        name="Work Meister S1 3P 18x11",
        brand="Work Wheels",
        category=PartCategory.WHEELS,
        description="3-piece stepped-lip Japanese wheel. Iconic show/stance/track aesthetic. Fully customizable offset and lip depth.",
        dimensions=Dimensions(length_mm=279, width_mm=279, height_mm=457),
        weight_kg=10.5,
        price_usd=1200,
        diameter_in=18,
        width_in=11,
        offset_mm=-5,
        bolt_pattern="5x114.3",
        material="Forged aluminum (3-piece)",
    ),
    Wheel(
        id="drag_steel_15",
        name="US Mags Drag Steel 15x10",
        brand="US Mags",
        category=PartCategory.WHEELS,
        description="Classic drag racing steel wheel. Heavy but incredibly strong. Designed to deform under bead load during launch. Accepts drag radials perfectly.",
        dimensions=Dimensions(length_mm=254, width_mm=254, height_mm=381),
        weight_kg=12.0,
        price_usd=180,
        diameter_in=15,
        width_in=10,
        offset_mm=-25,
        bolt_pattern="5x120.65",
        material="Steel",
    ),
]


# ═══════════════════════════════════════════════════════════════
#  TIRES  (5 options)
# ═══════════════════════════════════════════════════════════════

TIRES: list[Tire] = [
    Tire(
        id="michelin_ps4s_265_35_19",
        name="Michelin Pilot Sport 4S 265/35-19",
        brand="Michelin",
        category=PartCategory.TIRES,
        description="The gold standard UHP street tire. Exceptional wet and dry grip. Used OEM on most supercars.",
        dimensions=Dimensions(length_mm=265, width_mm=265, height_mm=660),
        weight_kg=11.8,
        price_usd=380,
        width_mm=265,
        aspect_ratio=35,
        rim_diameter_in=19,
        compound="Street UHP",
        max_load_kg=820,
        speed_rating="Y (300 km/h)",
        grip_index=0.87,
    ),
    Tire(
        id="michelin_cup2_265_35_19",
        name="Michelin Pilot Sport Cup 2 265/35-19",
        brand="Michelin",
        category=PartCategory.TIRES,
        description="Track-biased semi-slick. Road legal but warm-up dependent. Used on GT3 street cars and cup cars. Stunning dry grip.",
        dimensions=Dimensions(length_mm=265, width_mm=265, height_mm=660),
        weight_kg=11.2,
        price_usd=520,
        width_mm=265,
        aspect_ratio=35,
        rim_diameter_in=19,
        compound="Semi-Slick",
        max_load_kg=800,
        speed_rating="Y (300 km/h)",
        grip_index=0.95,
    ),
    Tire(
        id="hoosier_a7_245_40_17",
        name="Hoosier R7 245/40-17",
        brand="Hoosier",
        category=PartCategory.TIRES,
        description="Full slick compound. Track days and time attack only. Maximum lateral grip. Zero wet performance. SCCA solo eligible.",
        dimensions=Dimensions(length_mm=245, width_mm=245, height_mm=630),
        weight_kg=9.5,
        price_usd=280,
        width_mm=245,
        aspect_ratio=40,
        rim_diameter_in=17,
        compound="Slick",
        max_load_kg=760,
        speed_rating="W (270 km/h)",
        grip_index=1.0,
    ),
    Tire(
        id="nitto_nt05r_305_35_18_drag",
        name="Nitto NT05R Drag Radial 305/35-18",
        brand="Nitto",
        category=PartCategory.TIRES,
        description="Street-legal drag radial. Wide stance, flexible sidewall for launch. 60-foot times live and die by this tire. Best on a heated track.",
        dimensions=Dimensions(length_mm=305, width_mm=305, height_mm=660),
        weight_kg=16.0,
        price_usd=320,
        width_mm=305,
        aspect_ratio=35,
        rim_diameter_in=18,
        compound="Drag Radial",
        max_load_kg=1000,
        speed_rating="W (270 km/h)",
        grip_index=0.92,
    ),
    Tire(
        id="continental_sport7_225_45_17",
        name="Continental SportContact 7 225/45-17",
        brand="Continental",
        category=PartCategory.TIRES,
        description="Excellent all-rounder UHP tire. Great in rain too. Quieter than Cup2. Best street/occasional track tire for daily drivers.",
        dimensions=Dimensions(length_mm=225, width_mm=225, height_mm=630),
        weight_kg=10.8,
        price_usd=220,
        width_mm=225,
        aspect_ratio=45,
        rim_diameter_in=17,
        compound="Street UHP",
        max_load_kg=790,
        speed_rating="Y (300 km/h)",
        grip_index=0.84,
    ),
]


# ═══════════════════════════════════════════════════════════════
#  AGGREGATE CATALOG
# ═══════════════════════════════════════════════════════════════

ALL_PARTS: list = (
    ENGINES
    + TURBOS
    + TRANSMISSIONS
    + SUSPENSION_KITS
    + WHEELS
    + TIRES
    + ECUS
)

PARTS_BY_ID: dict = {p.id: p for p in ALL_PARTS}
CHASSIS_BY_ID: dict = {c.id: c for c in CHASSIS_LIST}


def search_parts(
    query: str | None = None,
    category: str | None = None,
    min_hp: int | None = None,
    max_weight_kg: float | None = None,
    max_price: int | None = None,
    chassis_id: str | None = None,
    limit: int = 50,
) -> list:
    results = list(ALL_PARTS)

    if category:
        results = [p for p in results if p.category.value == category]

    if query:
        q = query.lower()
        results = [
            p for p in results
            if q in p.name.lower()
            or q in p.brand.lower()
            or q in p.description.lower()
            or q in p.id.lower()
        ]

    if min_hp is not None:
        def has_hp(p):
            if hasattr(p, "horsepower_stock"):
                return p.horsepower_stock >= min_hp
            if hasattr(p, "max_hp_support"):
                return p.max_hp_support >= min_hp
            return True
        results = [p for p in results if has_hp(p)]

    if max_weight_kg is not None:
        results = [p for p in results if p.weight_kg <= max_weight_kg]

    if max_price is not None:
        results = [p for p in results if p.price_usd <= max_price]

    if chassis_id:
        chassis = CHASSIS_BY_ID.get(chassis_id)
        if chassis:
            results = [
                p for p in results
                if (not p.compatible_chassis or chassis_id in p.compatible_chassis)
                and chassis_id not in p.incompatible_chassis
            ]

    return results[:limit]
